mkpullfiles (and update) uses feed files now

diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,26 +1,119 @@
 #!/bin/bash
 
+# ------------------------------------------------------------------------------
+# settings                                                              settings
+# ------------------------------------------------------------------------------
+set -o errtrace  # any trap on ERR is inherited by shell functions,
+                 #   command substitutions, and commands executed in a subshell
+                 #   environment
+set -o nounset   # treat unset variables and parameters other than the special
+                 #   parameters "@" and "*" as an error when performing
+                 #   parameter expansion
+set -o pipefail  # the return value of a pipeline is the value of the last
+                 #   (rightmost) command to exit with a non-zero status, or
+                 #   zero if all commands in the pipeline exit successfully
+
+# set language
+export LANG="en_US.UTF-8"
+
+# use dot as decimal separator
+export LC_NUMERIC="en_US.UTF-8"
+
+# terminal colors
+readonly    NONE=$(tput sgr0)
+readonly     RED=$(tput setaf 1)
+readonly   GREEN=$(tput setaf 2)
+readonly  YELLOW=$(tput setaf 3)
+readonly    BLUE=$(tput setaf 4)
+readonly MAGENTA=$(tput setaf 5)
+readonly    CYAN=$(tput setaf 6)
+readonly   WHITE=$(tput setaf 7)
+
+# ------------------------------------------------------------------------------
+# functions                                                            functions
+# ------------------------------------------------------------------------------
+
+# -------
+# failmsg
+# -------
+#
+# This function prints a red colored message via stderr.
+#
+function failmsg()
+{
+  # push to stderr
+  echo -e "${RED}[FAIL]${NONE} $1" 1>&2
+}
+
+# -------
+# warnmsg
+# -------
+#
+# This function prints a yellow colored message via stderr.
+#
+function warnmsg()
+{
+  # push to stderr
+  echo -e "${YELLOW}[WARN]${NONE} $1" 1>&2
+}
+
+# -------
+# infomsg
+# -------
+#
+# This function prints a blue colored message via stderr.
+#
+function infomsg()
+{
+  # push to stderr
+  echo -e "${BLUE}[INFO]${NONE} $1" 1>&2
+}
+
+# -------
+# donemsg
+# -------
+#
+# This function prints a green colored message via stderr.
+#
+function donemsg()
+{
+  # push to stderr
+  echo -e "${GREEN}[DONE]${NONE} $1" 1>&2
+}
+
+# ------------------------------------------------------------------------------
+# commands                                                              commands
+# ------------------------------------------------------------------------------
+
+# check number of parameters
+if (( $# != 0 )) ; then
+
+  # notify user
+  failmsg "no parameters allowed"
+
+  # signalize trouble
+  exit 1
+
+fi
+
 # create temporary file
 TEMPFILE=$(mktemp)
 
 # clean up on exit
 trap 'rm -f "$TEMPFILE"' EXIT
 
-# create pull files for these podcast feeds
-for URL in "https://www.deutschlandfunk.de/podcast-aus-kultur-und-sozialwissenschaften.1149.de.podcast.xml" \
-           "https://www.deutschlandfunk.de/podcast-computer-und-kommunikation-beitraege.685.de.podcast.xml" \
-           "https://www.deutschlandfunk.de/podcast-dossier.1171.de.podcast.xml" \
-           "https://www.deutschlandfunk.de/podcast-forschung-aktuell.677.de.podcast.xml" \
-           "https://www.deutschlandfunk.de/podcast-hintergrund.725.de.podcast.xml" \
-           "https://www.deutschlandfunk.de/podcast-kulturfragen.912.de.podcast.xml" \
-           "https://www.deutschlandfunkkultur.de/podcast-kulturpresseschau.1060.de.podcast.xml" \
-           "https://www.deutschlandfunk.de/podcast-sternzeit.733.de.podcast.xml" \
-           "https://www.deutschlandfunk.de/podcast-wissenschaft-im-brennpunkt.741.de.podcast.xml" \
-           "https://www1.wdr.de/mediathek/audio/zeitzeichen/zeitzeichen-podcast-100.podcast"
+# operate all executables in the 'feeds/' directory
+find "feeds/"      \
+     -maxdepth "1" \
+     -type "f"     \
+     -perm "/u=x"  \
+     -print0       \
+| sort -z          \
+| while read -rd $'\0' FEEDFILE
 do
 
   # get podcast items
-  if ! ./fn.checkfeed "$URL" > "$TEMPFILE" ; then
+  if ! ./fn.checkfeed "$(bash "$FEEDFILE" -u)" > "$TEMPFILE" ; then
 
     # signalize trouble
     exit 1
@@ -28,7 +121,7 @@ do
   fi
 
   # create pull files
-  if ! ./fn.mkpullfiles "$TEMPFILE" ; then
+  if ! ./fn.mkpullfiles "$TEMPFILE" "$FEEDFILE" ; then
 
     # signalize trouble
     exit 1
@@ -46,14 +139,6 @@ find "pull/"                     \
 | sort                           \
 | nl
 echo
-
-# download episodes
-if [ "$1" == "-d" ] ; then
-
-  # just call next script
-  ./download
-
-fi
 
 # signalize success
 exit 0
