getnumbers updated

diff --git a/numbers/getnumber b/numbers/getnumber
--- a/numbers/getnumber
+++ b/numbers/getnumber
@@ -1,33 +1,88 @@
 #!/bin/bash
 
 # ------------------------------------------------------------------------------
-# arguments                                                            arguments
-# ------------------------------------------------------------------------------
-
-NUMBER="$1"
-
-# ------------------------------------------------------------------------------
 # settings                                                              settings
 # ------------------------------------------------------------------------------
+set -o errtrace  # any trap on ERR is inherited by shell functions,
+                 #   command substitutions, and commands executed in a subshell
+                 #   environment
+set -o nounset   # treat unset variables and parameters other than the special
+                 #   parameters "@" and "*" as an error when performing
+                 #   parameter expansion
+set -o pipefail  # the return value of a pipeline is the value of the last
+                 #   (rightmost) command to exit with a non-zero status, or
+                 #   zero if all commands in the pipeline exit successfully
+
+# set language
+export LANG="en_US.UTF-8"
+
+# use dot as decimal separator
+export LC_NUMERIC="en_US.UTF-8"
+
+# terminal colors
+readonly    NONE=$(tput sgr0)
+readonly     RED=$(tput setaf 1)
+readonly   GREEN=$(tput setaf 2)
+readonly  YELLOW=$(tput setaf 3)
+readonly    BLUE=$(tput setaf 4)
+readonly MAGENTA=$(tput setaf 5)
+readonly    CYAN=$(tput setaf 6)
+readonly   WHITE=$(tput setaf 7)
 
 # set directories
-readonly NUMDIR='/home/xi/Musik/zahlen/'
-readonly SRCDIR='/home/xi/Musik/zahlen/src/'
+readonly NUMDIR="$HOME/podcast/numbers/"
+readonly SRCDIR="$HOME/podcast/numbers/src/"
 
 # ------------------------------------------------------------------------------
 # functions                                                            functions
 # ------------------------------------------------------------------------------
 
-# ------
-# errmsg
-# ------
+# -------
+# failmsg
+# -------
 #
-# This function prints a red error message via stderr.
+# This function prints a red colored message via stderr.
 #
-function errmsg()
+function failmsg()
 {
   # push to stderr
-  echo -e "\e[1;91m[ERROR]\e[0m $1" 1>&2
+  echo -e "${RED}[FAIL]${NONE} $1" 1>&2
+}
+
+# -------
+# warnmsg
+# -------
+#
+# This function prints a yellow colored message via stderr.
+#
+function warnmsg()
+{
+  # push to stderr
+  echo -e "${YELLOW}[WARN]${NONE} $1" 1>&2
+}
+
+# -------
+# infomsg
+# -------
+#
+# This function prints a blue colored message via stderr.
+#
+function infomsg()
+{
+  # push to stderr
+  echo -e "${BLUE}[INFO]${NONE} $1" 1>&2
+}
+
+# -------
+# donemsg
+# -------
+#
+# This function prints a green colored message via stderr.
+#
+function donemsg()
+{
+  # push to stderr
+  echo -e "${GREEN}[DONE]${NONE} $1" 1>&2
 }
 
 # -----------
@@ -38,7 +93,8 @@ function errmsg()
 #
 function get_integer()
 {
-  sed -nre 's/^(-?[[:digit:]]+)$/\1+0/p' <<< "$1" | bc 2>'/dev/null'
+  # let bc add zero
+  sed -nre "s/^(-?)0*([[:digit:]]+)$/\1\2 + 0/p" <<< "$1" | bc 2>"/dev/null"
 }
 
 # -------
@@ -56,14 +112,14 @@ function wav2mp3()
        --strictly-enforce-ISO \
        --noreplaygain         \
        --cbr                  \
-       -b '128'               \
+       -b "128"               \
        -h                     \
        -p                     \
        --id3v2-only           \
-       --ta 'Linguatec'       \
-       --tl 'Spoken Numbers'  \
-       --ty "`date +%Y`"      \
-       --tg 'Other'           \
+       --ta "Linguatec"       \
+       --tl "Spoken Numbers"  \
+       --ty "$(date "+%Y")"   \
+       --tg "Other"           \
        --tn "$3"              \
        --tt "$3"              \
        "$1"                   \
@@ -81,8 +137,8 @@ function create_silence()
 {
   sox -V0 \
       -n  \
-      -b '24' -r '44100' -c '2' -e 'signed-integer' "$1" \
-      trim 0.000 "$2"
+      -b "24" -r "44100" -c "2" -e "signed-integer" "$1" \
+      trim "0.000" "$2"
 }
 
 # ----------------------
@@ -94,7 +150,7 @@ function create_silence()
 function remove_leading_silence()
 {
   # create temporary file
-  local TMP=$(mktemp --suffix='.wav')
+  local TMP=$(mktemp --suffix=".wav")
   
   # remove leading silence from wav file
   sox -V0 "$1" "$TMP" silence 1 0.1 -135d
@@ -112,7 +168,7 @@ function remove_leading_silence()
 function remove_trailing_silence()
 {
   # create temporary file
-  local TMP=$(mktemp --suffix='.wav')
+  local TMP=$(mktemp --suffix=".wav")
   
   # remove only trailing silence from wav file
   sox -V0 "$1" "$TMP" reverse silence 1 0.1 -135d reverse
@@ -131,10 +187,10 @@ function remove_trailing_silence()
 function splice_append()
 {
   # create temporary file
-  local TMP=$(mktemp --suffix='.wav')
+  local TMP=$(mktemp --suffix=".wav")
 
   # insert $2 at the end of $1
-  sox -V0 "$1" "$2" "$TMP" splice $(soxi -D "$1"),0.02,0.01
+  sox -V0 "$1" "$2" "$TMP" splice "$(soxi -D "$1"),0.02,0.01"
 
   # overwrite input file
   mv "$TMP" "$1"
@@ -151,46 +207,46 @@ function splice_append()
 function rig_up_number()
 {
   # name numbered arguments
-  WAVDIR="$1"
-  TARGET="$2"
-  FIGURE="$3"
+  local WAVDIR="$1"
+  local TARGET="$2"
+  local FIGURE="$3"
 
   # get involved filenames
   if (( FIGURE == 0 )); then
 
     # set filenames
-    FILE_TH=''
-    FILE_HN=''
-    FILE_TO='0.wav'
+    local FILE_TH=""
+    local FILE_HN=""
+    local FILE_TO="0.wav"
 
   else
 
     # split number
-    FILE_TH=$(bc <<< "$FIGURE/1000"     | sed -nre 's/^[123456789]$/&000.wav/p')
-    FILE_HN=$(bc <<< "$FIGURE%1000/100" | sed -nre 's/^[123456789]$/&00.wav/p')
-    FILE_TO=$(bc <<< "$FIGURE%100"      | sed -nre 's/^[123456789][[:digit:]]?$/&.wav/p')
+    local FILE_TH=$(bc <<< "$FIGURE/1000"     | sed -nre "s/^[123456789]$/&000.wav/p")
+    local FILE_HN=$(bc <<< "$FIGURE%1000/100" | sed -nre "s/^[123456789]$/&00.wav/p")
+    local FILE_TO=$(bc <<< "$FIGURE%100"      | sed -nre "s/^[123456789][[:digit:]]?$/&.wav/p")
 
   fi
 
   # insert source directory
-  FILE_TH=$(sed -re "s|.+|$WAVDIR&|" <<< "$FILE_TH")
-  FILE_HN=$(sed -re "s|.+|$WAVDIR&|" <<< "$FILE_HN")
-  FILE_TO=$(sed -re "s|.+|$WAVDIR&|" <<< "$FILE_TO")
+  local FILE_TH=$(sed -re "s|.+|$WAVDIR&|" <<< "$FILE_TH")
+  local FILE_HN=$(sed -re "s|.+|$WAVDIR&|" <<< "$FILE_HN")
+  local FILE_TO=$(sed -re "s|.+|$WAVDIR&|" <<< "$FILE_TO")
 
   # create temporary files
-  TEMPFILE_TH=$(mktemp --suffix='.wav')
-  TEMPFILE_HN=$(mktemp --suffix='.wav')
-  TEMPFILE_TO=$(mktemp --suffix='.wav')
+  local TEMPFILE_TH=$(mktemp --suffix=".wav")
+  local TEMPFILE_HN=$(mktemp --suffix=".wav")
+  local TEMPFILE_TO=$(mktemp --suffix=".wav")
 
   # no filename given
   if [ -z "$FILE_TH" ]; then
 
     # create silence
-    create_silence "$TEMPFILE_TH" '0.080'
+    create_silence "$TEMPFILE_TH" "0.080"
 
   else
 
-    # create copy
+    # duplicate file
     cp -f "$FILE_TH" "$TEMPFILE_TH"
 
     # more audio data to come
@@ -207,11 +263,11 @@ function rig_up_number()
   if [ -z "$FILE_HN" ]; then
 
     # create silence
-    create_silence "$TEMPFILE_HN" '0.080'
+    create_silence "$TEMPFILE_HN" "0.080"
 
   else
 
-    # create copy
+    # duplicate file
     cp -f "$FILE_HN" "$TEMPFILE_HN"
 
     # preceding wav file present
@@ -236,11 +292,11 @@ function rig_up_number()
   if [ -z "$FILE_TO" ]; then
 
     # create silence
-    create_silence "$TEMPFILE_TO" '0.080'
+    create_silence "$TEMPFILE_TO" "0.080"
 
   else
 
-    # create copy
+    # duplicate file
     cp -f "$FILE_TO" "$TEMPFILE_TO"
 
     # some audio data already present
@@ -266,34 +322,66 @@ function rig_up_number()
 }
 
 # ------------------------------------------------------------------------------
+# options                                                                options
+# ------------------------------------------------------------------------------
+
+# set default values
+OPMODE="MP3"
+
+# set options to accept
+readonly KNOWN_OPTIONS=":w"
+
+# check passed options
+while getopts "$KNOWN_OPTIONS" OPTION "$@"
+do
+
+  case "$OPTION" in
+
+    # wav file only
+    "w") OPMODE="WAV"
+         ;;
+
+    "?") failmsg "unknown option: -$OPTARG"
+         exit 1
+         ;;
+
+    ":") failmsg "missing argument: -$OPTARG <argument>"
+         exit 1
+         ;;
+
+  esac
+
+done
+
+# get number of positional parameters
+PPNUM=$(( $# - OPTIND + 1 ))
+
+# drop all parsed options
+shift $(( OPTIND - 1 ))
+
+# ------------------------------------------------------------------------------
 # commands                                                              commands
 # ------------------------------------------------------------------------------
 
-# set default value
-CREATEWAV='0'
+# check number of positional parameters
+if (( PPNUM != 1 )) ; then
 
-# check option
-if [ "$NUMBER" == '-w' ]; then
+  # notify user
+  failmsg "exactly one number needed to be passed in as argument"
 
-  # set flag
-  CREATEWAV='1'
-
-  # drop first argument
-  shift
-
-  # update number
-  NUMBER="$1"
+  # signalize trouble
+  exit 1
 
 fi
 
 # convert numeric argument
-NUMBER=$(get_integer "$NUMBER")
+NUMBER=$(get_integer "$1")
 
 # check number
-if [ -z "$NUMBER" ]; then
+if [ -z "$NUMBER" ] ; then
 
   # notify user
-  errmsg 'invalid number given...'
+  failmsg "invalid number: \"$1\""
 
   # signalize trouble
   exit 1
@@ -304,7 +392,7 @@ fi
 if (( NUMBER > 9999 )); then
 
   # notify user
-  errmsg "number too large: $NUMBER"
+  failmsg "number too large: $NUMBER"
 
   # signalize trouble
   exit 1
@@ -315,162 +403,98 @@ fi
 if (( NUMBER < 0 )); then
 
   # notify user
-  errmsg "number too small: $NUMBER"
+  failmsg "number too small: $NUMBER"
 
   # signalize trouble
   exit 1
 
 fi
 
-# create wav file
-if (( CREATEWAV == 1 )); then
+# check requested operation
+if [ "$OPMODE" == "MP3" ] ; then
 
-  # compile wav name
-  WAVFILE="$NUMDIR$NUMBER.wav"
+  # mp3 file requested
+  OUTFILE="$NUMDIR$NUMBER.mp3"
 
-  # check if wav file is already present
-  if [ -f "$WAVFILE" ]; then
+elif [ "$OPMODE" == "WAV" ] ; then
 
-    # show path
-    echo "$WAVFILE"
-
-    # signalize success
-    exit 0
-
-  fi
-
-  # compile name of source file
-  SRCFILE="$SRCDIR$NUMBER.wav"
-
-  # check if source file is already present
-  if [ -f "$SRCFILE" ]; then
-
-    # create copy
-    cp -f "$SRCFILE" "$WAVFILE"
-
-    # check if wav file is present now
-    if [ -f "$WAVFILE" ]; then
-
-      # show path
-      echo "$WAVFILE"
-
-      # signalize success
-      exit 0
-
-    else
-
-      # notify user
-      errmsg "unable to create wav file: \"$WAVFILE\""
-
-      # signalize trouble
-      exit 1
-
-    fi
-
-  fi
-
-  # rig up missing number
-  rig_up_number "$SRCDIR" "$WAVFILE" "$NUMBER"
-
-  # check if wav file is present now
-  if [ -f "$WAVFILE" ]; then
-
-    # show path
-    echo "$WAVFILE"
-
-    # signalize success
-    exit 0
-
-  else
-
-    # notify user
-    errmsg "unable to create wav file: \"$WAVFILE\""
-
-    # signalize trouble
-    exit 1
-
-  fi
-
-# create mp3 file
-else
-
-  # compile mp3 name
-  MP3FILE="$NUMDIR$NUMBER.mp3"
-
-  # check if mp3 file is already present
-  if [ -f "$MP3FILE" ]; then
-
-    # show path
-    echo "$MP3FILE"
-
-    # signalize success
-    exit 0
-
-  fi
-
-  # compile name of source file
-  SRCFILE="$SRCDIR$NUMBER.wav"
-
-  # check if source file is already present
-  if [ -f "$SRCFILE" ]; then
-
-    # create missing mp3 file
-    wav2mp3 "$SRCFILE" "$MP3FILE" "$NUMBER"
-
-    # check if mp3 file is present now
-    if [ -f "$MP3FILE" ]; then
-
-      # show path
-      echo "$MP3FILE"
-
-      # signalize success
-      exit 0
-
-    else
-
-      # notify user
-      errmsg "unable to create mp3 file: \"$MP3FILE\""
-
-      # signalize trouble
-      exit 1
-
-    fi
-
-  fi
-
-  # create temporary file
-  RIGNUM=$(mktemp --suffix='.wav')
-
-  # rig up missing number
-  rig_up_number "$SRCDIR" "$RIGNUM" "$NUMBER"
-
-  # create missing mp3 file
-  wav2mp3 "$RIGNUM" "$MP3FILE" "$NUMBER"
-
-  # remove expendable files
-  rm "$RIGNUM"
-
-  # check if mp3 file is present now
-  if [ -f "$MP3FILE" ]; then
-
-    # show path
-    echo "$MP3FILE"
-
-    # signalize success
-    exit 0
-
-  else
-
-    # notify user
-    errmsg "unable to create mp3 file: \"$MP3FILE\""
-
-    # signalize trouble
-    exit 1
-
-  fi
+  # wav file requested
+  OUTFILE="$NUMDIR$NUMBER.wav"
 
 fi
 
-# signalize trouble
-exit 1
+# requested file already present
+if [ -f "$OUTFILE" ] ; then
+
+  # push path to stdout
+  echo "$OUTFILE"
+
+  # stop here
+  exit 0
+
+fi
+
+# show progress
+infomsg "creating number file: $OUTFILE"
+
+# use direct path first
+SRCFILE="$SRCDIR$NUMBER.wav"
+
+# check if source file is missing
+if [ ! -f "$SRCFILE" ] ; then
+
+  # create temporary file
+  TEMPFILE=$(mktemp --suffix=".wav")
+
+  # clean up on exit
+  trap 'rm -f "$TEMPFILE"' EXIT
+
+  # try to rig up missing number
+  rig_up_number "$SRCDIR" "$TEMPFILE" "$NUMBER"
+
+  # check temporary wav file
+  if [ ! -s "$TEMPFILE" ]; then
+
+    # notify user
+    failmsg "unable to create wav file"
+
+    # signalize trouble
+    exit 1
+
+  fi
+
+  # use temporary wav file as source
+  SRCFILE="$TEMPFILE"
+
+fi
+
+# check requested operation
+if [ "$OPMODE" == "MP3" ] ; then
+
+  # create mp3 file
+  wav2mp3 "$SRCFILE" "$OUTFILE" "$NUMBER"
+
+elif [ "$OPMODE" == "WAV" ] ; then
+
+  # just copy the given source file
+  cp -f "$SRCFILE" "$OUTFILE"
+
+fi
+
+# check final output file
+if [ ! -s "$OUTFILE" ] ; then
+
+  # notify user
+  failmsg "unable to create file: \"$OUTFILE\""
+
+  # signalize trouble
+  exit 1
+
+fi
+
+# push absolute path to stdout
+readlink -e "$OUTFILE"
+
+# signalize success
+exit 0
 
